-- =================================================================
--  Prompt Market - Supabase Schema (RLS Disabled)
-- =================================================================
--  - 인증: Clerk
--  - 데이터베이스: Supabase
--  - 보안: RLS를 명시적으로 비활성화하고, 모든 접근 제어는
--    애플리케이션 서버(Next.js)에서 처리하는 것을 전제로 합니다.
-- =================================================================

-- 1. 사용자 프로필 테이블 (Clerk 사용자와 연결)
-- Clerk 사용자가 처음 생성될 때 트리거를 통해 자동으로 채워집니다.
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    clerk_id TEXT UNIQUE NOT NULL, -- Clerk user.id를 저장할 필드
    email TEXT UNIQUE,
    nickname TEXT,
    avatar_url TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ
);
COMMENT ON TABLE public.profiles IS '사용자 프로필 정보를 저장합니다. Clerk 인증 시스템과 연결됩니다.';
COMMENT ON COLUMN public.profiles.clerk_id IS 'Clerk 인증 시스템의 사용자 ID입니다.';

-- 2. 프롬프트(상품) 테이블
CREATE TABLE public.prompts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ,
    title TEXT NOT NULL,
    description TEXT,
    price INTEGER NOT NULL DEFAULT 0,
    prompt_text TEXT, -- 구매자에게만 공개될 실제 프롬프트
    image_urls TEXT[], -- 이미지 URL 배열
    tags TEXT[], -- 태그 배열
    rating NUMERIC(2, 1) DEFAULT 0.0,
    review_count INTEGER DEFAULT 0,
    download_count INTEGER DEFAULT 0,
    view_count INTEGER DEFAULT 0,
    file_url TEXT, -- 다운로드 가능한 파일 경로 (선택 사항)
    is_published BOOLEAN DEFAULT true NOT NULL
);
COMMENT ON TABLE public.prompts IS '판매되는 AI 프롬프트 상품 정보입니다.';
COMMENT ON COLUMN public.prompts.prompt_text IS '구매한 사용자만 접근 가능한 프롬프트 본문입니다.';

-- 3. 장바구니 테이블
CREATE TABLE public.carts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    prompt_id UUID NOT NULL REFERENCES public.prompts(id) ON DELETE CASCADE,
    CONSTRAINT unique_cart_item UNIQUE (user_id, prompt_id) -- 사용자는 동일 상품을 중복해서 담을 수 없음
);
COMMENT ON TABLE public.carts IS '사용자의 장바구니 항목을 저장합니다.';

-- 4. 구매 내역 테이블
CREATE TABLE public.purchases (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    buyer_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    prompt_id UUID NOT NULL REFERENCES public.prompts(id) ON DELETE CASCADE,
    amount_paid INTEGER NOT NULL, -- 실제 결제된 금액
    payment_order_id TEXT UNIQUE, -- 토스페이먼츠 주문 ID
    payment_provider TEXT DEFAULT 'toss_payments'
);
COMMENT ON TABLE public.purchases IS '사용자의 상품 구매 기록입니다.';
COMMENT ON COLUMN public.purchases.payment_order_id IS '결제사에서 발급한 고유 주문 ID로, 중복 결제를 방지합니다.';

-- 5. 판매자 대기 목록 테이블
CREATE TABLE public.seller_waitlist (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    portfolio_url TEXT,
    categories TEXT[],
    message TEXT,
    processed BOOLEAN DEFAULT false NOT NULL
);
COMMENT ON TABLE public.seller_waitlist IS '판매자 등록을 신청한 사용자 목록입니다.';

-- =================================================================
--  자동화: 새 사용자 가입 시 프로필 생성 트리거
-- =================================================================

-- 새 사용자가 auth.users에 추가될 때 public.profiles 테이블에 프로필을 생성하는 함수
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, clerk_id, email)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'clerk_id', -- Clerk ID는 JWT의 메타데이터에서 가져옵니다.
    NEW.email
  );
  RETURN NEW;
END;
$$;

-- auth.users 테이블에 INSERT가 발생할 때마다 위 함수를 실행하는 트리거
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

COMMENT ON FUNCTION public.handle_new_user IS 'Clerk에서 새 사용자가 생성될 때 Supabase의 public.profiles에 미러링합니다.';

-- =================================================================
--  보안: Row Level Security (RLS) 명시적 비활성화
-- =================================================================
-- 중요: 아래 설정은 모든 사용자가 API 키를 통해 데이터에 접근할 수 있게 하므로,
-- 반드시 Next.js 서버 측에서 데이터 접근 권한을 철저히 제어해야 합니다.

ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.prompts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.carts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchases DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.seller_waitlist DISABLE ROW LEVEL SECURITY;
